### ISSUE TITLE
Unable to sign up or login

### ISSUE THREAD

**Issue by camjac251** [flaviusdolha/Yosemite#1]
I came across this repo looking for a file host and it looks pretty cool judging by the PDF. I tried to run it myself but I am unable to sign up or login it seems. There's no error that appears either so I'm not sure what's going on. Is this app production ready?

**Comment by mzch** [comment]
me too. I tried to signup but nothing happned.

**Comment by flaviusdolha** [comment]
Did you try to run the server on your computer? You have to type in the terminal:
`node app.js`

**Comment by mzch** [comment]
Yes, I run `node app.js` and access to app's port via proxy.

**Comment by flaviusdolha** [comment]
Also, did you install mongodb and run in the terminal: `mongod`?

**Comment by mzch** [comment]
Yes. Both `Yosemite` and `mongod` are running.

Yosemite reported only below:
```
 5月 21 09:16:08 lb systemd[1]: Started Yosemite.
 5月 21 09:16:08 lb node[7871]: Warning: connect.session() MemoryStore is not
 5月 21 09:16:08 lb node[7871]: designed for a production environment, as it will leak
 5月 21 09:16:08 lb node[7871]: memory, and will not scale past a single process.
```

**Comment by camjac251** [comment]
I installed the needed packages with `npm install` and also installed Mongo too. When I click the login button or Sign up button, it will stay stuck on a loading icon on the tab. It never goes beyond that.

**Comment by camjac251** [comment]
I think the user is registered correctly as I get this in the console for the script when attempting to sign up again with an existing username
```
ctor [UserExistsError]: A user with the given username is already registered
    at /root/Yosemite/node_modules/passport-local-mongoose/index.js:237:17
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

However it will not continue after pressing login. It just hangs for a while
